{
  "intents": [
    {
      "tag": "saludo",
      "examples": [
        "hola",
        "buenas",
        "buenos dias",
        "buenas tardes",
        "buenas noches",
        "hola como estan",
        "quiubo",
        "que tal",
        "hey",
        "hi",
        "hola buen dia",
        "hola buenas",
        "buen dia",
        "buen dia como estan",
        "saludos",
        "hola que tal",
        "hola estan",
        "hola hay alguien",
        "hola me pueden ayudar",
        "hola necesito ayuda",
        "hola buenas tardes",
        "hola buenas noches",
        "hola quiubo",
        "holaa",
        "holaaa",
        "buenass",
        "buenas tardes como estan",
        "buenas noches necesito pedir",
        "hola quisiera pedir",
        "hola quiero hacer un pedido",
        "hola quiero comprar",
        "hello",
        "holis",
        "hola buen dia como estan",
        "ola",
        "ola como estan",
        "buenas noches estan",
        "hola hay servicio",
        "buen dia hay productos",
        "buenas tardes quisiera pedir",
        "hola que hay",
        "hola que tienen hoy",
        "hola disponibles",
        "buenos dias me ayudan",
        "hola me pueden colaborar",
        "hola alguien me atiende",
        "hola atienden",
        "hola servicio al cliente",
        "hola es el numero de pedidos",
        "hola es aqui donde se pide",
        "que tal estan",
        "hola buen dia necesito algo"
      ]
    },
    {
      "tag": "consulta_catalogo",
      "examples": [
        "donde puedo ver los productos",
        "como hago el pedido",
        "como se pide",
        "como funciona",
        "como compro",
        "donde estan los productos",
        "me puedes pasar el catalogo",
        "quiero ver que tienen",
        "que tienen disponible",
        "que hay hoy",
        "que productos tienen",
        "me mandas el menu",
        "tienes catalogo",
        "link del catalogo",
        "me pasas el link",
        "como agrego al carrito",
        "donde esta el carrito",
        "como se hace el pedido",
        "no se como pedir",
        "no entiendo como pedir",
        "me explicas como pedir",
        "como es el proceso",
        "cual es el proceso",
        "como funciona el pedido",
        "pasos para pedir",
        "catalogo por favor",
        "muestrame los productos",
        "que productos manejan",
        "tienen pagina web",
        "tienen app",
        "donde compro",
        "me mandas info de los productos",
        "info de los productos",
        "quiero saber que tienen"
      ]
    },
    {
      "tag": "consulta_producto",
      "examples": [
        "tienen aguacate",
        "hay manzanas",
        "tienen papa",
        "hay tomate",
        "tienen cebolla",
        "hay platano",
        "tienen naranja",
        "hay limon",
        "tienen fresas",
        "hay mora",
        "busco verduras",
        "necesito frutas",
        "quiero comprar aguacate",
        "me interesa el aguacate",
        "cuanto vale el aguacate",
        "precio del aguacate",
        "tienen zanahoria",
        "hay espinaca",
        "tienen brocoli",
        "hay lechuga",
        "tienen pepino",
        "hay piña",
        "tienen mango",
        "precio de la papaya",
        "cuanto cuesta la naranja",
        "tienen banano",
        "hay uvas",
        "quiero saber el precio",
        "cuanto vale",
        "cuanto cuesta",
        "precio por kilo",
        "me interesa",
        "tienen eso",
        "hay de ese",
        "tienen sofas",
        "hay camas",
        "tienen mesas",
        "precio del sofa",
        "cuanto vale la cama",
        "tienen comedores",
        "hay sillas",
        "busco muebles",
        "necesito un sofa",
        "quiero una cama",
        "tienen sala",
        "precio de la sala",
        "hay salas",
        "sofas camas",
        "tienen sofa cama",
        "busco sofa cama",
        "quiero ver comedores",
        "hay mesas de comedor",
        "busco camisa",
        "tienen pantalones",
        "hay vestidos",
        "quiero zapatos",
        "tienen tenis",
        "hay blusas",
        "busco medicamentos",
        "tienen pastillas",
        "hay vitaminas",
        "quiero pan",
        "tienen tortas",
        "hay empanadas",
        "tienen sala lucerna",
        "precio sala imperial",
        "hay sofa glamour",
        "sala home precio",
        "tienen sofa cama morgan",
        "sala armonia",
        "precio sala epica",
        "tienen sala nube",
        "sala princesa precio",
        "sala dubai cuanto vale",
        "comedor toscana precio",
        "tienen comedor luxury",
        "precio comedor imperial",
        "comedor atlas",
        "hay comedor roma",
        "precio comedor cairo",
        "tienen sofa cama aplatinado",
        "sala confort precio",
        "sala chester hay",
        "precio sala oasis",
        "sala deluxe cuanto",
        "tienen comedor alma",
        "precio comedor essence",
        "sala danesa precio",
        "comedor majestic hay",
        "sala l gala",
        "sala amber precio",
        "hay sala clasica",
        "comedor campestre precio",
        "comedor eclipse hay",
        "tienen sala home",
        "sala london precio",
        "sala candy cuanto cuesta",
        "comedor sirena",
        "tienen sala santorini",
        "sala olivia precio"
      ]
    },
    {
      "tag": "consulta_domicilio",
      "examples": [
        "hacen domicilio",
        "llegan a mi zona",
        "llegan a kennedy",
        "llegan a suba",
        "llegan a bosa",
        "llegan a chapinero",
        "hacen envio",
        "hay domicilio",
        "tienen domicilio",
        "llegan hasta aca",
        "cubren mi zona",
        "entregan en bogota",
        "llegan a fontibon",
        "llegan a engativa",
        "llegan a usaquen",
        "llegan a teusaquillo",
        "llegan a barrios unidos",
        "llegan a puente aranda",
        "llegan a tunjuelito",
        "llegan a soacha",
        "entregan en soacha",
        "cubren soacha",
        "cuanto vale el domicilio",
        "cuanto cuesta el envio",
        "es gratis el domicilio",
        "cobran por el envio",
        "hay costo de envio",
        "cuanto me cobran de domicilio",
        "tienen cobertura en mi barrio",
        "entregan en mi direccion",
        "llegan a mi casa",
        "hacen entrega a domicilio",
        "tienen servicio de entrega",
        "es gratis el envio",
        "entregan a domicilio",
        "tienen servicio a domicilio",
        "hacen entrega en casa",
        "van a mi casa",
        "llegan a mi barrio",
        "cubren todo bogota",
        "entregan en el norte",
        "entregan en el sur",
        "llegan al occidente",
        "llegan al oriente",
        "llegan a chia",
        "llegan a municipios",
        "llegan a cundinamarca"
      ]
    },
    {
      "tag": "hora_pedido",
      "examples": [
        "a que hora entregan",
        "que hora llega el pedido",
        "en cuanto tiempo llega",
        "cuanto se demora",
        "hora de entrega",
        "cuando llega",
        "que horario tienen",
        "horario de entregas",
        "hasta que hora piden",
        "hasta que hora reciben pedidos",
        "a que hora cierran",
        "cuando puedo pedir",
        "a que hora abren",
        "hay entrega hoy",
        "pueden entregar hoy",
        "lo tienen para hoy",
        "entrega el mismo dia",
        "entrega inmediata",
        "cuando es la proxima entrega",
        "horario de atencion",
        "que dias entregan",
        "entregan sabado",
        "entregan domingo",
        "entregan festivos",
        "entregan todos los dias",
        "cuando puedo recibir el pedido",
        "cuanto tarda en llegar",
        "tiempo de entrega",
        "a que hora debo pedir para recibir hoy",
        "si pido ahora llega hoy",
        "si pido esta noche llega manana",
        "que hora es el limite para pedir",
        "hora limite de pedidos",
        "hasta las cuantas reciben",
        "desde que hora pueden pedir",
        "que horario de pedidos tienen",
        "hay pedido nocturno",
        "pedidos madrugada",
        "entregan en la tarde",
        "entregan en la manana",
        "horario de domiciliarios"
      ]
    },
    {
      "tag": "metodo_pago",
      "examples": [
        "como se paga",
        "formas de pago",
        "aceptan tarjeta",
        "pago con nequi",
        "pago con daviplata",
        "aceptan efectivo",
        "como pago",
        "metodos de pago",
        "puedo pagar con tarjeta",
        "aceptan transferencia",
        "pago online",
        "pago contra entrega",
        "cuando se paga",
        "se paga antes o despues",
        "pago anticipado",
        "se paga cuando llega",
        "aceptan bre-b",
        "tienen datafono",
        "aceptan pse",
        "puedo pagar con transferencia",
        "cobran por adelantado",
        "pago al recibir",
        "es contra entrega",
        "hay que pagar antes",
        "tienen que ver algo con pago",
        "como funciona el pago",
        "pago con movil",
        "billetera digital",
        "pago digital"
      ]
    },
    {
      "tag": "pedido_no_ha_llegado",
      "examples": [
        "no ha llegado mi pedido",
        "donde esta mi pedido",
        "mi pedido no llego",
        "estoy esperando el pedido",
        "ya son las 12 y no ha llegado",
        "llevo horas esperando",
        "cuanto mas tarda mi pedido",
        "por que no ha llegado",
        "el domiciliario no ha llegado",
        "nadie ha llegado",
        "ya pedi hace rato y nada",
        "mi mercado no llego",
        "estoy en la casa esperando",
        "ya es tarde y no llega",
        "donde quedo mi pedido",
        "se perdio mi pedido",
        "no saben nada de mi pedido",
        "mi pedido esta perdido",
        "debio llegar antes",
        "el pedido no aparece",
        "sigo esperando",
        "nada del pedido",
        "aun no llega"
      ]
    },
    {
      "tag": "queja_servicio",
      "examples": [
        "mal servicio",
        "estoy molesto",
        "estan fallando",
        "muy mal",
        "pesimo servicio",
        "no vuelvo a pedir",
        "ultima vez que compro aca",
        "me llegaron productos malos",
        "el producto estaba danado",
        "me mandaron cosas en mal estado",
        "no me gusto el servicio",
        "tengo una queja",
        "quiero quejarme",
        "quisiera reportar un problema",
        "me defraudaron",
        "pedi una cosa y me mandaron otra",
        "el pedido estaba incompleto",
        "me faltaron productos",
        "me cobraron de mas",
        "precio diferente al del catalogo",
        "no me dieron lo que pedi",
        "el servicio es muy malo",
        "no quedé satisfecho",
        "tengo un reclamo",
        "muy mala experiencia",
        "no recomiendo este servicio",
        "nunca mas pido aqui",
        "que mala atencion",
        "pedi papas y me mandaron zanahorias",
        "me mandaron frutas en mal estado",
        "las verduras llegaron podridas",
        "el pedido llego incompleto",
        "me faltaron cosas",
        "me cobraron mas de lo que valia",
        "el precio no coincide",
        "cometieron un error en mi pedido",
        "tuve mala experiencia",
        "el domiciliario fue grosero",
        "el repartidor fue irrespetuoso",
        "no me trataron bien",
        "perdieron mi pedido",
        "me dieron lo de otro"
      ]
    },
    {
      "tag": "consulta_estado_pedido",
      "examples": [
        "como va mi pedido",
        "estado de mi pedido",
        "ya salio el pedido",
        "cuando sale mi pedido",
        "en que estado esta mi pedido",
        "ya lo enviaron",
        "ya fue despachado",
        "ya tienen mi pedido",
        "recibieron mi orden",
        "confirme mi pedido",
        "ya se proceso mi pedido",
        "ya fue aceptado",
        "sigue en proceso mi pedido",
        "cuanto falta para que salga",
        "ya esta listo",
        "prepararon mi pedido",
        "ya lo tienen",
        "lo estan alistando",
        "lo despacharon ya"
      ]
    },
    {
      "tag": "fuera_de_tema",
      "examples": [
        "como te llamas",
        "eres un bot",
        "eres una persona",
        "quien eres",
        "que eres tu",
        "eres humano",
        "cuantos anos tienes",
        "donde estan ubicados",
        "tienen local",
        "tienen tienda fisica",
        "donde queda la tienda",
        "tienen redes sociales",
        "instagram de ustedes",
        "facebook de ustedes",
        "tienen whatsapp de atencion",
        "quien es el dueno",
        "como se llama la empresa",
        "tienen pagina web",
        "url de la pagina",
        "que empresa son",
        "de donde son",
        "pueden hacer algo diferente a mercado",
        "venden otras cosas",
        "puedo pedirles otra cosa",
        "hacen mandados",
        "van a supermercado",
        "van a hacer mercado",
        "que mas ofrecen",
        "otros servicios que tengan",
        "saben de cocina",
        "me dan recetas",
        "como se prepara el aguacate",
        "receta con tomate",
        "que puedo hacer con las frutas",
        "tienen servicio de asesor nutricional",
        "me recomiendan dieta",
        "saben de nutricion",
        "me ayudan con recetas",
        "me pueden dar ideas para cocinar",
        "que cocino con esto"
      ]
    },
    {
      "tag": "agradecimiento",
      "examples": [
        "gracias",
        "muchas gracias",
        "mil gracias",
        "gracias por todo",
        "muy amable",
        "gracias por la info",
        "gracias por ayudarme",
        "excelente atencion",
        "muy buen servicio",
        "todo bien gracias",
        "perfecto gracias",
        "listo gracias",
        "ok gracias",
        "entendido gracias",
        "claro gracias",
        "gracias buenas",
        "buenas gracias",
        "gracias que esten bien",
        "gracias me ayudaron mucho",
        "super gracias",
        "genial gracias",
        "de acuerdo gracias",
        "chevere gracias",
        "bacano gracias",
        "gracias totales"
      ]
    },
    {
      "tag": "despedida",
      "examples": [
        "adios",
        "hasta luego",
        "chao",
        "bye",
        "nos vemos",
        "hasta pronto",
        "que este bien",
        "que les vaya bien",
        "cuidense",
        "hasta la proxima",
        "buenas noches adios",
        "listo chao",
        "ok chao",
        "de acuerdo chao",
        "me despido",
        "hasta despues",
        "hasta otra",
        "fue un placer",
        "un abrazo",
        "mucho exito"
      ]
    },
    {
      "tag": "confirmar_pedido",
      "examples": [
        "confirmar",
        "si confirmo",
        "si quiero confirmar",
        "confirmo el pedido",
        "si lo confirmo",
        "acepto el pedido",
        "si acepto",
        "esta bien confirmo",
        "listo confirmo",
        "ok confirmo",
        "de acuerdo confirmo",
        "si esta bien confirmo",
        "correcto confirmo",
        "si correcto",
        "si todo esta bien"
      ]
    },
    {
      "tag": "rechazar_pedido",
      "examples": [
        "rechazar",
        "no quiero",
        "cancelo el pedido",
        "no lo quiero",
        "cancelen el pedido",
        "no gracias",
        "mejor no",
        "lo cancelo",
        "quiero cancelar",
        "no acepto",
        "rechaza el pedido",
        "no confirmo",
        "no esta bien",
        "tiene error el pedido",
        "hay un error cancelo"
      ]
    },
    {
      "tag": "datos_entrega",
      "examples": [
        "mi nombre es juan garcia calle 13 kennedy lunes",
        "juan perez carrera 45 suba martes",
        "me llamo maria calle 80 engativa miercoles",
        "juan garcia calle 13 45 67 kennedy lunes",
        "nombre pedro direccion calle 45 localidad bosa dia viernes",
        "carlos rodriguez carrera 7 chapinero jueves",
        "ana martinez transversal 78 fontibon sabado",
        "luis gonzalez avenida 68 teusaquillo martes",
        "paula jimenez diagonal 45 barrios unidos lunes",
        "mi nombre carlos calle 100 suba el martes",
        "maria lopez cr 50 kennedy para el jueves",
        "jorge calle 80 bis engativa viernes",
        "datos entrega nombre juan direccion calle 13 localidad kennedy dia martes",
        "te mando mis datos juan garcia calle 45 bosa sabado",
        "aqui mis datos carlos calle 80 suba lunes",
        "nombres andrea torres direccion carrera 68 localidad engativa dia miercoles",
        "me llamo camila vargas vivo en calle 127 suba para el lunes",
        "nicolas rojas cra 7 chapinero norte jueves",
        "valentina calle 45 sur kennedy sabado",
        "pedro martinez transversal 33 teusaquillo viernes",
        "sebastian gomez av 80 engativa lunes",
        "laura garcia calle 100 suba martes",
        "nombre juan apellido garcia direccion calle 13 45 67 localidad kennedy dia lunes",
        "soy carlos vivo en cr 50 48 32 suba quiero entrega el viernes",
        "hola mi nombre es maria mi dir es calle 80 bis 90 15 barrio engativa dia martes"
      ]
    },
    {
      "tag": "consulta_precio_minimo",
      "examples": [
        "cual es el minimo de pedido",
        "hay un minimo",
        "cuanto es lo minimo que puedo pedir",
        "desde cuanto puedo pedir",
        "hay pedido minimo",
        "cuanto tengo que pedir minimo",
        "cual es el valor minimo",
        "desde que monto hacen domicilio",
        "que minimo necesito comprar",
        "hay un limite minimo",
        "puedo pedir poco",
        "puedo hacer un pedido pequeno",
        "necesito comprar minimo cuanto",
        "para que sea gratis el domicilio",
        "desde cuanto es gratis el envio",
        "que necesito para envio gratis",
        "cuanto necesito para domicilio gratis",
        "puedo pedir solo una cosa",
        "puedo pedir un kilo",
        "puedo hacer un pedido pequeno",
        "hay limite de compra",
        "puedo pedir poco hoy",
        "si pido menos de 100 hay domicilio",
        "que pasa si pido menos del minimo",
        "y si no alcanzo el minimo",
        "puedo sumar con otra persona",
        "pedido compartido"
      ]
    },
    {
      "tag": "cambiar_pedido",
      "examples": [
        "quiero cambiar mi pedido",
        "puedo modificar el pedido",
        "quiero agregar algo al pedido",
        "quiero quitar algo del pedido",
        "me equivoque en el pedido",
        "hice mal el pedido",
        "puedo cambiar algo",
        "quiero hacer un cambio",
        "modifiquen el pedido",
        "agreguenme algo",
        "quitenme algo del pedido",
        "cambie el pedido",
        "quiero un producto diferente",
        "me equivoque de producto",
        "el pedido tiene un error",
        "quiero corregir el pedido",
        "cambienme la cantidad",
        "quiero mas de algo",
        "quiero menos de algo",
        "me arrepenti de algo que pedi",
        "no quiero ese producto",
        "cambienme ese por otro",
        "agrego algo mas",
        "le aumento la cantidad a algo",
        "quiero menos cantidad",
        "ya no quiero ese producto",
        "sustituyan ese producto",
        "reemplacen eso por otra cosa",
        "modifiquen mi orden"
      ]
    },
    {
      "tag": "pedir_hablar_humano",
      "examples": [
        "quiero hablar con una persona",
        "me comunican con alguien",
        "quiero hablar con un asesor",
        "hay alguien que me pueda atender",
        "necesito hablar con un humano",
        "me pasan con alguien",
        "quiero atencion personalizada",
        "pueden llamarme",
        "quiero que me llamen",
        "necesito hablar con alguien",
        "asesor por favor",
        "me atiende una persona",
        "no quiero hablar con el bot",
        "quiero un agente",
        "agente por favor",
        "hablar con humano",
        "me comunicas con soporte",
        "soporte humano",
        "necesito ayuda de una persona real",
        "quiero atencion humana",
        "comunicame con el administrador",
        "hay un supervisor",
        "quiero hablar con el jefe",
        "me puedes conectar con alguien",
        "prefiero hablar con una persona",
        "el bot no me ayuda",
        "no entiendo al bot",
        "necesito ayuda humana",
        "quiero que me ayude alguien de verdad",
        "atencion en vivo"
      ]
    },
    {
      "tag": "consulta_descuentos",
      "examples": [
        "tienen descuentos",
        "hay promociones",
        "tienen ofertas",
        "algun descuento",
        "hay algo en oferta",
        "precios especiales",
        "descuento para clientes frecuentes",
        "hay codigo de descuento",
        "tienen cupones",
        "precio especial",
        "algo mas economico",
        "me pueden dar un descuento",
        "hay algo mas barato",
        "precio de mayorista",
        "compro en cantidad hay descuento",
        "si compro mas me dan descuento",
        "precio al por mayor",
        "precios de mayoreo",
        "hay rebajas",
        "estan en oferta",
        "tienen programa de fidelidad",
        "descuento por primera compra",
        "bienvenida oferta",
        "cliente nuevo descuento",
        "si traigo mas clientes hay algo",
        "referidos descuento",
        "si compro siempre hay descuento",
        "cliente frecuente beneficio",
        "plan de lealtad",
        "puntos por compra"
      ]
    },
    {
      "tag": "pensar_luego",
      "examples": [
        "lo pienso",
        "despues pido",
        "mas tarde pido",
        "lo voy a pensar",
        "voy a pensarlo",
        "mas tarde te escribo",
        "luego hago el pedido",
        "mas tarde vuelvo",
        "no por ahora",
        "tal vez despues",
        "quizas mas tarde",
        "ahorita no",
        "por el momento no",
        "cuando pueda pido",
        "cuando necesite pido",
        "cuando quiera pido",
        "no por ahora gracias",
        "tal vez la proxima",
        "lo dejo para despues",
        "otro dia pido",
        "no por ahora te escribo despues",
        "gracias pero no por ahora",
        "lo evaluo y te digo",
        "necesito consultarlo",
        "lo hablo con alguien y te escribo",
        "cuando tome la decision te escribo",
        "lo dejo pendiente",
        "quizas la proxima semana",
        "tengo que ver si tengo plata",
        "cuando tenga dinero pido"
      ]
    },
    {
      "tag": "festivos_horario_especial",
      "examples": [
        "entregan domingo",
        "trabajan domingo",
        "hay pedidos el domingo",
        "entregan festivos",
        "trabajan festivos",
        "hay domicilio festivos",
        "trabajan manana que es festivo",
        "hay servicio el festivo",
        "trabajan en semana santa",
        "hay entregas en diciembre",
        "entregan navidad",
        "trabajan en fin de ano",
        "hay servicio el primero de enero",
        "trabajan el dia de la madre",
        "hay entrega el sabado",
        "trabajan el sabado",
        "horario especial",
        "hay cambios en el horario",
        "horario festivos",
        "atienden festivos",
        "trabajaron ayer festivo",
        "hubo servicio el festivo pasado",
        "como queda el servicio en vacaciones",
        "hay cambios en navidad",
        "tienen servicio semana santa completa",
        "que dias no trabajan",
        "dias de descanso",
        "cuando no hay servicio",
        "que fechas no trabajan"
      ]
    },
    {
      "tag": "dejar_vecino_porteria",
      "examples": [
        "si no estoy lo dejan con el portero",
        "pueden dejarlo en porteria",
        "lo dejan con el vecino",
        "si no hay nadie lo dejan",
        "pueden dejarlo en la puerta",
        "lo dejan con alguien",
        "si no estoy como hacen",
        "que pasa si no estoy",
        "puedo dejar indicaciones especiales",
        "indicaciones de entrega",
        "dejar con el portero",
        "dejar en porteria",
        "si no contesto el telefono",
        "si no abren la puerta",
        "dejar con vecino del 201",
        "dejar con la senora del primero",
        "instrucciones especiales de entrega",
        "hay alguien que reciba",
        "otra persona puede recibir",
        "puede recibir mi familiar"
      ]
    }
  ]
}